/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "style": {
    name: "style",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "orb": {
    name: "orb",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/elevenlabs-ui/ui/orb.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/orb.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "waveform": {
    name: "waveform",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/elevenlabs-ui/ui/waveform.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/waveform.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "live-waveform": {
    name: "live-waveform",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/elevenlabs-ui/ui/live-waveform.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/live-waveform.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shimmering-text": {
    name: "shimmering-text",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/elevenlabs-ui/ui/shimmering-text.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/shimmering-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "audio-player": {
    name: "audio-player",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "registry/elevenlabs-ui/ui/audio-player.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/audio-player.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "message": {
    name: "message",
    description: "",
    type: "registry:ui",
    registryDependencies: ["avatar"],
    files: [{
      path: "registry/elevenlabs-ui/ui/message.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/message.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "conversation": {
    name: "conversation",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [{
      path: "registry/elevenlabs-ui/ui/conversation.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/conversation.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "response": {
    name: "response",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/elevenlabs-ui/ui/response.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/response.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-visualizer": {
    name: "bar-visualizer",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/elevenlabs-ui/ui/bar-visualizer.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/bar-visualizer.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "voice-picker": {
    name: "voice-picker",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","badge","command","popover","https://ui.elevenlabs.io/r/orb.json","https://ui.elevenlabs.io/r/audio-player.json"],
    files: [{
      path: "registry/elevenlabs-ui/ui/voice-picker.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/voice-picker.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "voice-button": {
    name: "voice-button",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","https://ui.elevenlabs.io/r/live-waveform.json"],
    files: [{
      path: "registry/elevenlabs-ui/ui/voice-button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/voice-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "conversation-bar": {
    name: "conversation-bar",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","https://ui.elevenlabs.io/r/live-waveform.json","card","separator","textarea"],
    files: [{
      path: "registry/elevenlabs-ui/ui/conversation-bar.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/conversation-bar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "software-purchase-card": {
    name: "software-purchase-card",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","card","badge"],
    files: [{
      path: "registry/elevenlabs-ui/ui/software-purchase-card.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/ui/software-purchase-card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "speaker-01": {
    name: "speaker-01",
    description: "EL-01 Speaker",
    type: "registry:block",
    registryDependencies: ["https://ui.elevenlabs.io/r/audio-player.json","https://ui.elevenlabs.io/r/orb.json","https://ui.elevenlabs.io/r/waveform.json","button","card"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/speaker-01/page.tsx",
      type: "registry:page",
      target: "app/speaker/page.tsx"
    },{
      path: "registry/elevenlabs-ui/blocks/speaker-01/components/speaker.tsx",
      type: "registry:component",
      target: "components/speaker.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/speaker-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"900px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "transcriber-01": {
    name: "transcriber-01",
    description: "Transcriber",
    type: "registry:block",
    registryDependencies: ["https://ui.elevenlabs.io/r/live-waveform.json","button","card","scroll-area","separator"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/transcriber-01/page.tsx",
      type: "registry:page",
      target: "app/transcriber-01/page.tsx"
    },{
      path: "registry/elevenlabs-ui/blocks/transcriber-01/actions/transcribe.ts",
      type: "registry:file",
      target: "app/transcriber-01/actions/transcribe.ts"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/transcriber-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "voice-chat-01": {
    name: "voice-chat-01",
    description: "Voice chat 1",
    type: "registry:block",
    registryDependencies: ["https://ui.elevenlabs.io/r/orb.json","https://ui.elevenlabs.io/r/shimmering-text.json","button","card","https://ui.elevenlabs.io/r/message.json","https://ui.elevenlabs.io/r/response.json","https://ui.elevenlabs.io/r/conversation.json","scroll-area"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/voice-chat-01/page.tsx",
      type: "registry:page",
      target: "app/voice-chat/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/voice-chat-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["agents"],
    meta: {"iframeHeight":"800px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "voice-chat-02": {
    name: "voice-chat-02",
    description: "Voice chat 2",
    type: "registry:block",
    registryDependencies: ["https://ui.elevenlabs.io/r/orb.json","https://ui.elevenlabs.io/r/shimmering-text.json","button","card"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/voice-chat-02/page.tsx",
      type: "registry:page",
      target: "app/voice-chat/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/voice-chat-02/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["agents"],
    meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "voice-chat-03": {
    name: "voice-chat-03",
    description: "Voice chat 3",
    type: "registry:block",
    registryDependencies: ["https://ui.elevenlabs.io/r/conversation-bar.json","https://ui.elevenlabs.io/r/conversation.json","https://ui.elevenlabs.io/r/message.json","https://ui.elevenlabs.io/r/orb.json","https://ui.elevenlabs.io/r/response.json","tooltip","card","button"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/voice-chat-03/page.tsx",
      type: "registry:page",
      target: "app/voice-chat/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/voice-chat-03/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["agents"],
    meta: {"iframeHeight":"800px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "music-player-01": {
    name: "music-player-01",
    description: "Music player with playlist",
    type: "registry:block",
    registryDependencies: ["https://ui.elevenlabs.io/r/audio-player.json","button","scroll-area"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/music-player-01/page.tsx",
      type: "registry:page",
      target: "app/music-player/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/music-player-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "music-player-02": {
    name: "music-player-02",
    description: "Simple music player",
    type: "registry:block",
    registryDependencies: ["https://ui.elevenlabs.io/r/audio-player.json","card"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/music-player-02/page.tsx",
      type: "registry:page",
      target: "app/music-player/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/music-player-02/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"400px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "voice-form-01": {
    name: "voice-form-01",
    description: "Voice-fill form",
    type: "registry:block",
    registryDependencies: ["https://ui.elevenlabs.io/r/voice-button.json","https://ui.elevenlabs.io/r/live-waveform.json","button","card","form","input"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/voice-form-01/page.tsx",
      type: "registry:page",
      target: "app/voice-form/page.tsx"
    },{
      path: "registry/elevenlabs-ui/blocks/voice-form-01/schema.ts",
      type: "registry:file",
      target: "app/voice-form/schema.ts"
    },{
      path: "registry/elevenlabs-ui/blocks/voice-form-01/actions/voice-to-form.ts",
      type: "registry:file",
      target: "app/voice-form/actions/voice-to-form.ts"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/voice-form-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"700px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "voice-nav-01": {
    name: "voice-nav-01",
    description: "Voice-nav site navigation",
    type: "registry:block",
    registryDependencies: ["https://ui.elevenlabs.io/r/voice-button.json","button","card"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/voice-nav-01/page.tsx",
      type: "registry:page",
      target: "app/voice-nav/page.tsx"
    },{
      path: "registry/elevenlabs-ui/blocks/voice-nav-01/actions/voice-to-site.ts",
      type: "registry:file",
      target: "app/voice-nav/actions/voice-to-site.ts"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/voice-nav-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["audio"],
    meta: {"iframeHeight":"900px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "software-purchase-01": {
    name: "software-purchase-01",
    description: "Software purchase approval card",
    type: "registry:block",
    registryDependencies: ["software-purchase-card","separator"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/software-purchase-01/page.tsx",
      type: "registry:page",
      target: "app/software-purchase/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/software-purchase-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["forms"],
    meta: {"iframeHeight":"900px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "billing-information-01": {
    name: "billing-information-01",
    description: "Billing information management",
    type: "registry:block",
    registryDependencies: ["button","card"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/billing-information-01/page.tsx",
      type: "registry:page",
      target: "app/billing-information/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/billing-information-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["billing"],
    meta: {"iframeHeight":"700px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "card-display-01": {
    name: "card-display-01",
    description: "Credit card display",
    type: "registry:block",
    registryDependencies: ["card"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/card-display-01/page.tsx",
      type: "registry:page",
      target: "app/card-display/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/card-display-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["billing"],
    meta: {"iframeHeight":"400px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "payment-method-01": {
    name: "payment-method-01",
    description: "Payment methods management",
    type: "registry:block",
    registryDependencies: ["button","card","tooltip"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/payment-method-01/page.tsx",
      type: "registry:page",
      target: "app/payment-method/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/payment-method-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["billing"],
    meta: {"iframeHeight":"500px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "transaction-history-01": {
    name: "transaction-history-01",
    description: "Transaction history with date picker",
    type: "registry:block",
    registryDependencies: ["button","calendar","card","popover"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/transaction-history-01/page.tsx",
      type: "registry:page",
      target: "app/transaction-history/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/transaction-history-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["billing"],
    meta: {"iframeHeight":"800px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "invoices-01": {
    name: "invoices-01",
    description: "Invoices list with status badges",
    type: "registry:block",
    registryDependencies: ["badge","button","separator"],
    files: [{
      path: "registry/elevenlabs-ui/blocks/invoices-01/page.tsx",
      type: "registry:page",
      target: "app/invoices/page.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/blocks/invoices-01/page.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: ["billing"],
    meta: {"iframeHeight":"700px","container":"w-full bg-surface min-h-svh flex px-4 py-12 items-center md:py-20 justify-center min-w-0","mobile":"component"},
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/elevenlabs-ui/hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/hooks/use-mobile.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "audio-player-demo": {
    name: "audio-player-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/audio-player.json","button","card","scroll-area"],
    files: [{
      path: "registry/elevenlabs-ui/examples/audio-player-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/audio-player-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "orb-demo": {
    name: "orb-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/orb.json","button"],
    files: [{
      path: "registry/elevenlabs-ui/examples/orb-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/orb-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "waveform-demo": {
    name: "waveform-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/waveform.json"],
    files: [{
      path: "registry/elevenlabs-ui/examples/waveform-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/waveform-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "live-waveform-demo": {
    name: "live-waveform-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/live-waveform.json","button"],
    files: [{
      path: "registry/elevenlabs-ui/examples/live-waveform-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/live-waveform-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-visualizer-demo": {
    name: "bar-visualizer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/bar-visualizer.json","button"],
    files: [{
      path: "registry/elevenlabs-ui/examples/bar-visualizer-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/bar-visualizer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "message-demo": {
    name: "message-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/message.json","https://ui.elevenlabs.io/r/response.json"],
    files: [{
      path: "registry/elevenlabs-ui/examples/message-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/message-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "response-demo": {
    name: "response-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/response.json"],
    files: [{
      path: "registry/elevenlabs-ui/examples/response-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/response-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "shimmering-text-demo": {
    name: "shimmering-text-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/shimmering-text.json"],
    files: [{
      path: "registry/elevenlabs-ui/examples/shimmering-text-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/shimmering-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "voice-picker-demo": {
    name: "voice-picker-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/voice-picker.json","https://ui.elevenlabs.io/r/audio-player.json"],
    files: [{
      path: "registry/elevenlabs-ui/examples/voice-picker-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/voice-picker-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "voice-button-demo": {
    name: "voice-button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/voice-button.json"],
    files: [{
      path: "registry/elevenlabs-ui/examples/voice-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/voice-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "conversation-bar-demo": {
    name: "conversation-bar-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/conversation-bar.json"],
    files: [{
      path: "registry/elevenlabs-ui/examples/conversation-bar-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/conversation-bar-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "conversation-demo": {
    name: "conversation-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["https://ui.elevenlabs.io/r/message.json","https://ui.elevenlabs.io/r/response.json","https://ui.elevenlabs.io/r/conversation.json"],
    files: [{
      path: "registry/elevenlabs-ui/examples/conversation-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/conversation-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "software-purchase-card-demo": {
    name: "software-purchase-card-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["software-purchase-card"],
    files: [{
      path: "registry/elevenlabs-ui/examples/software-purchase-card-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/elevenlabs-ui/examples/software-purchase-card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }